protocol = "{{ cookiecutter.first_daemon_kind }}"
doc = ""
traits = ["is-daemon"]

[links]
source = "https://github.com/yaq-project/{{ cookiecutter.project_slug }}"
bugtracker = "https://github.com/yaq-project/{{ cookiecutter.project_slug }}/-/issues"

[installation]
PyPI = "https://pypi.org/project/{{ cookiecutter.project_slug }}"

[config]

[state]

[messages]

